version: '3.8'
services:
    postgres:
        image: postgres:10.5
        restart: always
        environment: 
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes:
          #- ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./database/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
          # copy the sql script to fill tables
          - ./database/sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    tokenservice:
      depends_on:
        - postgres
      build: .
      restart: on-failure
      ports:
        - '8088:8088'
      container_name: tokenservice
      environment:
        SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:postgresql://postgres:5432/postgres",
          "spring.datasource.username" : "postgres",
          "spring.datasource.password" : "postgres",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
          "server.port" : "8088",
          "server.address" : "0.0.0.0"
        }'
      volumes:
        - .m2:/root/.m2
      stdin_open: true
      tty: true
